trigger:
  branches:
    include:
    - master
  tags:
    include:
    - "*"

jobs:
- job: Build
  strategy:
    matrix:
      linux:
        imageName: 'ubuntu-16.04'
        CXX: g++
      macOS:
        imageName: 'macOS-10.14'
        CXX: clang++

  pool:
    vmImage: $(imageName)
  steps:
  - template: scripts/azure-linux_mac.yml

- job: Docker
  dependsOn: Build
  condition: succeeded()

  pool:
    vmImage: 'ubuntu-18.04'

  strategy:
    matrix:
      tiledb-mariadb:
        dockerfile: docker/Dockerfile
        repository: tiledb/tiledb-mariadb
        context: .
      tiledb-mariadb-server:
        dockerfile: docker/Dockerfile
        repository: tiledb/tiledb-mariadb-server
        context: .

  steps:
  - template: scripts/build-images.yml
