name: docker

# TODO: In the future make this workflow_run, however, that one does not support tags only branches
# TODO: Or make this take a list of tags... Sadly this cannot be done now, only string can be passed
on:
  workflow_dispatch:
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        configuration:
          - dockerfile: "Dockerfile"
            repository: "tiledb/tiledb-mariadb"
    steps:
      - uses: actions/checkout@v3
      - name: Build and push develop
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/${{ matrix.configuration.dockerfile }}
          push: true
          tags: |
            ${{ matrix.configuration.repository }}:dev
          build-args: |
            MYTILE_VERSION=${{ github.ref_name }}
      - name: Build and push release
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/${{ matrix.configuration.dockerfile }}
          push: false
          tags: |
            ${{ matrix.configuration.repository }}:latest
            ${{ matrix.configuration.repository }}:${{ github.ref_name }}
          build-args: |
            MYTILE_VERSION=${{ github.ref_name }}
